### ISSUE TITLE
compile error.

### ISSUE THREAD

**Issue by tyson239** [Metapyziks/SanAndreasUnity#21]
Hello, there's a compile error.
Assets\Scripts\Generated\ProtocolBuffers.Serializer.cs
It told me that Could not find "SilentOrbit", and at the last of the file, seems it's a not finished script?

```
        /// <summary>Serialize into a JSON string</summary>
        public static void SerializeJson(TextWriter writer, Vector2 instance)
        {
            writer.Write("{");

```

**Comment by prateeksach** [comment]
I also got this error, fixed using the suggestion Unity gave me but then I also get a new namespace not found error for the following line:

`public MessageTable<INetworkMessage> MessageTable { get { return _messageTable; } }
`

It suggests I'm missing an assembly reference (pointing to 'MessageTable') but not sure why. I'm currently using Unity 5.3.5 on Mac El Capitan.

@Metapyziks , any chance you can help?

**Comment by tomes11** [comment]
Same here. Fixed one error, another 40 popped up. Maybe a little more instruction how to use it would be great!.
